[package]
name = "egg-mode-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.1"
egg-mode = "0.15"
tokio = { version = "0.2", features = ["full"] }
